### ISSUE TITLE
Migrate news items to Eclipse Newsroom

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/jquery-eclipsefdn-api#14]
We need to install our news & event widget on the following site:

- [x] Eclipse.org
- [x] Eclipse Cloud Development Tools
- [x] Eclipse Edge Native
- [x] Eclipse IoT
- [x] Jakarta EE
- [x] OpenADx
- [ ] openGENESIS
- [x] OpenHW Group
- [ ] OpenMDM
- [x] openMobility
- [x] openPASS
- [x] Science
- [x] Eclipse Sparkplug

## Plan

1. Graeham will help migrate existing content to the newsroom website. I will reach out to Graeham and show him the steps for migrating the news and events.

    * I will let @shanda-eclipse decide if we should migrate all news or a subset of the news archive. 
    * We should also review current news items on Eclipse Newsroom and decide if we should tag them for publication on our others sites.

2. Once Graeham is done migrating the content for a site, he will post an update on this issue and this will be our queue for installing the news & event widget.

### Expectations for installing the widget

(I will use iot.eclipse.org as example.)

1. Replace the news and  list with js widget. It's important to do what we can to avoid tweaks to the look and feel of the page as this is outside of the scope of this bug.

2. Create or replace the news and event archive: 

- https://iot.eclipse.org/events/
- https://iot.eclipse.org/news/

I expect these pages to stay but the data should be pulled-in from newsroom.eclipse.org

**Comment by shanda-eclipse** [comment]
I migrated the **ECD tools** news items to the newsroom. I would say a site that size would take about 20 min uninterrupted. 

I have also copied the news items into a word doc so I can cross-reference them once the new widget is installed to makes sure I didn't miss anything. Let me know when the widget is on ecdtools.eclipse.org and I will check it out.

**Comment by shanda-eclipse** [comment]
I also moved over the 1 upcoming event for ECD tools.

**Comment by chrisguindon** [comment]
Thanks @shanda-eclipse!

@autumnfound has started installing the widget: https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/27

**Comment by chrisguindon** [comment]
@shanda-eclipse,

The news widget will be live in about 10 minutes on ecdtools.eclipse.org. 

With that said, I have a question for you!

Under our events, we have a **"View all"**" link and on Eclipse.org we have a **"Subscribe to our RSS-feed"** and View all link and I think we should be consistent with this.

What do you think of the following suggestion:

[RSS ICON] | View all | Submit News

The new "Submit News" would link to newsroom.eclipse.org/node/add/news. I am also suggesting that we remove the "Subscribe to our RSS-feed" text in favor of an orange icon.

**Comment by shanda-eclipse** [comment]
This article: https://newsroom.eclipse.org/news/announcements/eclipse-foundation-releases-eclipse-theia-10-true-open-source-alternative-visual is not showing up on the ECD tools site. One difference from the other articles that worked: it's marked to be posted on eclipse.org and edctools.

**Comment by shanda-eclipse** [comment]
> Under our events, we have a **"View all"**" link and on Eclipse.org we have a **"Subscribe to our RSS-feed"** and View all link and I think we should be consistent with this.
> 
> What do you think of the following suggestion:
> 
> [RSS ICON] | View all | Submit News
> 
> The new "Submit News" would link to newsroom.eclipse.org/node/add/news. I am also suggesting that we remove the "Subscribe to our RSS-feed" text in favor of an orange icon.

+1

**Comment by shanda-eclipse** [comment]
Can we also drop it down to 3 news items before the "View all"?

**Comment by chrisguindon** [comment]
@shanda-eclipse +1 It should be 3 news item for this site!

**Comment by chrisguindon** [comment]
I made the change on the website.

**Comment by shanda-eclipse** [comment]
OpenADX news migrated. No future events to migrate.

**Comment by shanda-eclipse** [comment]
openMobility news and events migrated.

**Comment by chrisguindon** [comment]
The widget should now be installed on openMobility. We have it ready for openADX but since they have a team for making changes on the website, I will contact them to let them know about this change before we go live with the widget.

**Comment by chrisguindon** [comment]
I sent an email to openMobility to let then know of this new change!

**Comment by shanda-eclipse** [comment]
OpenPASS has no news or events to migrate.

**Comment by GraehamHui** [comment]
Eclipse EdgeNative news has been migrated. 1 event migrated

**Comment by shanda-eclipse** [comment]
Sparkplug news and events migrated.

**Comment by shanda-eclipse** [comment]
Science news and events migrated. Not sure why they have separated our community news and announcements, but I have marked articles this way.

**Comment by chrisguindon** [comment]
@shanda-eclipse Edge native, openadx and Sparkplug are now using our news widget!

**Comment by shanda-eclipse** [comment]
openGENESIS - doesn't appear to have a website, just a wiki page

**Comment by shanda-eclipse** [comment]
OpenHW group news and events migrated.

**Comment by shanda-eclipse** [comment]
Status update on what we still have to migrate (for my own clarification):
 OpenMDM
 Eclipse IoT
 Jakarta EE

**Comment by chrisguindon** [comment]
> openGENESIS - doesn't appear to have a website, just a wiki page

Correct! We are still working on the website!  This is the current state: 
https://eclipsefdn-opengenesis.netlify.app/

Sharon is currently working on the content for this or finding someone who will write the content for the site!

**Comment by chrisguindon** [comment]
@shanda-eclipse We should communicate this change next with Eclipse IoT, Jakarta EE, Eclipse Science, and OpenHWGroup before we switch them over.

**Comment by shanda-eclipse** [comment]
> @shanda-eclipse We should communicate this change next with Eclipse IoT, Jakarta EE, Eclipse Science, and OpenHWGroup before we switch them over.

Let's reach out to Eclipse Science, and OpenHWGroup now. I think Eclipse IoT and Jakarta EE might take us a bit more time to migrate (they are the big ones).

**Comment by chrisguindon** [comment]
I agree that we might not be able to do Eclipse IoT and Jakarta EE next week but I think they will appreciate the heads up even if we do this in a month!

I will reach out to Eclipse Science and OpenHWGroup directly. 

Is it possible to announce this in one of our WG Marketing meetings for Jakarta and Eclipse IoT?

**Comment by shanda-eclipse** [comment]
Formating for OpenADX events is off: https://openadx.eclipse.org/. "View all" and "Submit event" should be at the bottom, and the content should run the full column width. 
![image](https://user-images.githubusercontent.com/61751191/82821265-c7467d00-9e71-11ea-9cc0-5b7dec7af785.png)

**Comment by chrisguindon** [comment]
I will take a look! 

I might need to tweak the HTML of the page as we did not design this website. I will try to submit a change that will make this section consistent with what we normally do.

**Comment by shanda-eclipse** [comment]
Now that we have a bunch of events posted on the working group sites, I noticed they are posting in reverse date order. Can we sort based on the closest upcoming date to furthest out?

**Comment by shanda-eclipse** [comment]
> Is it possible to announce this in one of our WG Marketing meetings for Jakarta and Eclipse IoT?

I briefed Ioana and Shabnam on the plan. They will notify working groups on next marketing call.

**Comment by chrisguindon** [comment]
> > Is it possible to announce this in one of our WG Marketing meetings for Jakarta and Eclipse IoT?
> 
> I briefed Ioana and Shabnam on the plan. They will notify working groups on next marketing call.

Great! I've sent an email to notify the Eclipse Science WG and OpenHWGroup!

**Comment by GraehamHui** [comment]
openMDM news items have been uploaded. No upcoming events to upload.

**Comment by chrisguindon** [comment]
@GraehamHui @shanda-eclipse, is it possible to prioritize OpenHWGroup next? 

They started to submit news items on the Eclipse Newsroom website but the newsroom widget is not on the site yet.

@autumnfound Please create a patch to install Newsroom widget for OpenHWGroup next.

**Comment by shanda-eclipse** [comment]
OpenHW was migrated a few weeks ago. We only have IoT and Jakarta EE left to migrate.

**Comment by chrisguindon** [comment]
Thanks @shanda-eclipse, OpenHW Group now has our Newsroom widget.

**Comment by chrisguindon** [comment]
I consider openpass done:
https://eclipsefdn-openpass.netlify.app/

The current website does not have a news section but we are almost ready to launch the new Hugo website which already has the newsroom widget.

**Comment by chrisguindon** [comment]
@autumnfound The following are ready to use Eclipse Newsroom:

- Eclipse Science
- OpenMDM - This is a drupal site, I will take this on.
- OpenGenesis - The website is not live, this is not a high priority.

Once these are done, we will just need to finalize IoT and Jakarta.ee. We kept the bigger sites for last!

**Comment by shanda-eclipse** [comment]
IoT news and events have been migrated and the working group has been notified of the change. Please implement API.

**Comment by chrisguindon** [comment]
> IoT news and events have been migrated and the working group has been notified of the change. Please implement API.

We committed https://github.com/EclipseFdn/iot.eclipse.org/pull/464. The site should be pulling news from newsroom in about 5-10 minutes.

**Comment by chrisguindon** [comment]
Eclipse Science was also done today! Thanks @autumnfound 

https://github.com/EclipseFdn/science.eclipse.org/pull/13

**Comment by GraehamHui** [comment]
Jakarta EE community news, announcements, and events have been uploaded to the CMS. Additionally, the Jakarta EE steering committee is on board with the CMS transfer.

**Comment by chrisguindon** [comment]
Thanks @GraehamHui! This is great news!

**Comment by chrisguindon** [comment]
Jarkarta.ee is now done!

**Comment by chrisguindon** [comment]
We are migrating openmdm to Hugo this quarter. The new site will leverage our news widget. 

OpenGenesis is not a live website. We can fix it whenever we decide to finalize the site.
