### ISSUE TITLE
Manage featured stories via our Eclipse Newsroom CMS

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/jquery-eclipsefdn-api#16]
We receive many requests to update our "featured-footer" sections across many of our various web properties.

To reduce the time needed to make these updates, I would like to propose that we create a new content-type in the Eclipse Newsroom website to manage featured-footers.

I would expect this to be similar to how we manage news or event. We would include a publish_to field that will allow us to chose which featured story.

I think the only cons for doing this is that we will need to be more strict with the design of our featured footer since we will need to make this work on all sites. We will need to create something generic and since we plan on automatic this, we will lose our ability to create custom designs for each of our sites.

Similar to our Event websites, we could plan on creating a few different layout configurations that folks can pick from while creating the featured-story.

This could be a good project to work on in Q3 if foundation staff are interested.

However, before we start, we will need to do define the list of fields for this new content type.

I will get us started with the obvious:

- Title
- Body
- start_date
- end_date
- layout (List of predefined layouts for the featured footer. Would require some help from our Creative Specialist, @ChristieWittEclipse 
- default*: True/False

* Default stories are used as a back up if all other featured stories for the site has expired. For some context, we usually tag the Eclipse IDE release as a default.

**Comment by ChristieWittEclipse** [comment]
+1 thanks @chrisguindon, I've added this to my backlog.

**Comment by shanda-eclipse** [comment]
Additional considerations:
- Can we have footers on rotation if more than 1 is applicable at a time
- Background image for the banner should be a standard size to keep design simple (and allow us to apply banners to multiple sites without uploading different dimensions)
- Each working group could have 1 banner that's not time-sensitive as a default (ex. sign-up for our newsletter, follow us on social, etc)

To add to list of fields:
- Button text
- Button link

**Comment by chrisguindon** [comment]
I suggested via Bug 563674 - Add a "Featured Project" to the home page https://bugs.eclipse.org/bugs/show_bug.cgi?id=563674 that we could leverage this new form to capture "Featured Projects" information.

If we decide to go down this path, we would now have 3 types of "Featured Content"

1. Featured Story (Below Jumbotron)
2. Featured Story Footer
3. Featured Project

**Comment by ChristieWittEclipse** [comment]
@chrisguindon here are the lists of required fields for Featured story and Featured story Footer:
-Title
-Body
-CTA button text
-CTA button link
-Start_date
-End_date
-1. Layout Light - This will default to a white background with black text for all Working Group websites, with the exception of Eclipse.org and Jakarta.ee websites that will use their current light default images. The CTA button will use the brands secondary color. Sample:
![Light-color-block-sample](https://user-images.githubusercontent.com/58480647/88094783-1d7a2880-cb62-11ea-97cd-0eac697b7e3b.png)
-2. Layout Dark - This will default to a background color using the brands primary color with white text. The CTA button will use the brands secondary color. Sample:
![Dark-color-block-sample](https://user-images.githubusercontent.com/58480647/88094826-2ec33500-cb62-11ea-9eec-68d599879555.png)
-Default*: True/False - Default stories are used as a back up if all other featured stories for the site has expired. For some context, we usually tag the Eclipse IDE release as a default.

**Comment by autumnfound** [comment]
Some suggestions for fields:
**Prefix text field**
This field is used in some production banners and is the text that is set above the title. This field is optional (along with the body) to make up the extra contextual content for a banner.

**A preview field**
This would pre-render a preview of what your data would look like on the Eclipse home page. This would allow users to sanity check the content and layout in a browser before submitting it. Because we're using a JavaScript plugin to render this, it should be relatively straight forward to have code on the page to render it
 
**"Advanced settings" dropdown**
This dropdown would contain things like the raw HTML option for advanced users (which I talk about below), options to add classes to the various fields. This gives us flexibility to add things like the underline seen on Jakarta EE content. While you would have to know classes to add and such, its an option to give more flexibility while not having to know how to format HTML.

**Raw HTML option**
  - We can pre-populate this or have an example underneath for easier use of more advanced use-cases.
  - We should not be accepting script or iframe elements in this, as its a security vulnerability.   
  - Would give us flexibility for edge cases where non-standard content is wanted/needed.

With this content, would we be removing the option to have custom-defined image backgrounds? They are more complicated to add, but they make the content more dynamic and I want to be sure it wasn't forgotten accidentally.

**Comment by chrisguindon** [comment]
This is awesome everyone!

I will consider all this feedback for building the first prototype for this. I will update this bug once that's done!

**Comment by ChristieWittEclipse** [comment]
@autumnfound to answer your Question: 

With this content, would we be removing the option to have custom-defined image backgrounds? They are more complicated to add, but they make the content more dynamic and I want to be sure it wasn't forgotten accidentally.

Answer: I would remove the option to have custom defined image backgrounds for websites aside from Eclipse.org and Jakarta.ee. They do make the content more dynamic, but I don't think it's feasible for me to commit to graphic output for every news item on every WG website unfortunately.

**Comment by chrisguindon** [comment]
`Answer: I would remove the option to have custom defined image backgrounds for websites aside from Eclipse.org and Jakarta.ee. They do make the content more dynamic, but I don't think it's feasible for me to commit to graphic output for every news item on every WG website unfortunately.`

I don't want to add this type of complexity. Let's keep it simple for phase 1. I will use the fields that @ChristieWittEclipse suggested via https://github.com/EclipseFdn/jquery-eclipsefdn-api/issues/16#issuecomment-662046858

We can look at adding advanced features that @autumnfound suggested in the future but let see how this works out first!

**Comment by chrisguindon** [comment]
We now have an API for our featured-stories:
https://newsroom.eclipse.org/api/featured_story

@autumnfound is now working on implementing the required changes to our jquery plugin in order to fetch the data from this new API!

**Comment by chrisguindon** [comment]
This is now live on www.eclipse.org. I scheduled a quick training session with @jph152 and @karenmcnaughton for next Monday to discuss how this works.

Similar to what we did with Events/News, we will install this new widget on all our WG sites in Q4.

**Comment by chrisguindon** [comment]
@flora8984461 please install this new feature on all our WG sites.

**Comment by flora8984461** [comment]
- [x]  Eclipse Cloud Development Tools 
- [x]  Eclipse Edge Native
- [x]  Eclipse IoT
- [x]  Jakarta EE
- [x]  OpenADx (did not have featured stuff, added featured footer)
- [x]  openGENESIS 
- [x]  OpenHWGroup (did not have featured stuff, added featured footer)
- [x]  OpenMDM (The hugo site is done but not live yet. More info see: https://github.com/EclipseFdn/openmdm.org/issues/1)
- [x]  openMobility
- [x]  openPASS
- [x]  Science
- [x]  Eclipse Sparkplug
- [x]  events.eclipse.org (eclipse_org)
- [x]  osdforums.org (openhwgroup)
- [x] jakartaone.org (jakarta_ee)
