### ISSUE TITLE
Need the ability to fetch  press-releases only

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/jquery-eclipsefdn-api#40]
The plugin allows us to fetch announcements and community news separately. 

We now have a use case for only displaying Press-Releases:
https://www.eclipse.org/org/press-release/

Our PR page is missing new content that was created via the newsroom.

**Comment by chrisguindon** [comment]
The API does support this notion:
https://newsroom.eclipse.org/api/news?page=1&pagesize=3&parameters[is_press_release]=1

**Comment by autumnfound** [comment]
This was merged in previously
