### ISSUE TITLE
Fetch news from newsroom.eclipse.org

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/jquery-eclipsefdn-api#8]
We plan on creating news on newsroom.eclipse.org from now on and we need a way to fetch news for each of our site.

We decided to create a js widget that will allow us to display news by fetching data from it's API:
https://newsroom.eclipse.org/api/news?parameters[news_type]=community_news&parameters[publish_to]=eclipse_org

Requirements:

- Pagination for news archive, i.e https://jakarta.ee/news/announcements/
- Ability to limit posts (pagesize=5), i.e https://www.eclipse.org
- Ability to filter by news_type (parameters[news_type]=community_news and parameters[news_type]=announcements) 
- Ability to filter by publish_to (parameters[publish_to]=eclipse_org)

**Comment by autumnfound** [comment]
This has been merged in and is in use on production
